name: New Issue
description: Description
title: "Title "
labels: ["bsdk-lang"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make an issue!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Enter a brief description
      placeholder: Please include a summary. Please also include relevant motivation and context. 
      value: "Description"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Domain
      description: Select domain of Contribution
      options:
        - Design
        - Develop
        - bsdk Lang
        - UI/UX
        - Other
    validations:
      required: true
  - type: dropdown
    id: contribtype
    attributes:
      label: Type of Contribution
      multiple: true
      options:
        - Addition
        - Refactoring
        - Enhancement
        - Documentation
        - Others
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/DulLabs/bsdk-lang/blob/develop/README.md)
      options:
        - label: I follow [Contributing Guidelines](https://github.com/DulLabs/bsdk-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bsdk-lang/blob/develop/README.md) of bsdk-lang.
          required: true
